### ISSUE TITLE
any progress?

### ISSUE THREAD

**Issue by ATouhou** [tylerofathenry/Etre_Worpress#1]
Hi.
Any progress on this?

**Comment by tylers-username** [comment]
Hi Atouhou,

Yes. It's been about a month since I've dabbled with it but the module is functional. The WordPress plugin/half of this module is a bit messy, but contained and functional as well. I'll be sure to update this repository so that you have something to work with.

I'll close this issue once I've updated everything here.

**Comment by tylers-username** [comment]
Please have a look at the master branch now.
